### Spatial Cross Validation

library(sf)
library(tidyverse)
library(dplyr)
library(magrittr)
library(mapview)
library(spdep)
library(caret)
library(ckanr) 
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot)
library(jtools)     
library(stargazer) 
library(broom)
library(tufte)
library(rmarkdown)
library(kableExtra)
library(tidycensus)
library(RSocrata)
library(viridis)
library(spatstat) 
library(raster)
library(knitr)
library(rgdal)

setwd("C:\\PENN\\2022\\MUSA_801_Practicum\\MUSA_801_PPR\\data\\output")

modelPlaces <- st_read('modelPlaces.GEOJSON')