---
title: "dataExploratory"
author: "Shaun"
date: "1/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(vroom)
```

## moves2018

```{r moves2018, warning=FALSE}
moves2018 <- vroom("D:/OneDrive/WORK/Upenn/Spring_MUSA_801_Practicum/PPR - Safegraph/Data/movesData/moves_2018.csv")
moves2018
```

## moves_monthly2020

```{r moves_monthly2020, warning=FALSE}
moves_monthly2020 <- vroom("D:/OneDrive/WORK/Upenn/Spring_MUSA_801_Practicum/PPR - Safegraph/Data/movesData/moves_monthly2020.csv")
moves_monthly2020
```

## brand_info

```{r brand_info, warning=FALSE}
brand_info <- vroom("D:/OneDrive/WORK/Upenn/Spring_MUSA_801_Practicum/PPR - Safegraph/Data/SG_Data/Philadelphia-Camden-WilmingtonPA-NJ-DE-MDMSA-CORE_POI-2021_11-2021-12-17/brand_info.csv")
brand_info
```


## core_poi

```{r core_poi, warning=FALSE}
core_poi <- vroom("D:/OneDrive/WORK/Upenn/Spring_MUSA_801_Practicum/PPR - Safegraph/Data/SG_Data/Philadelphia-Camden-WilmingtonPA-NJ-DE-MDMSA-CORE_POI-2021_11-2021-12-17/core_poi.csv")
core_poi
```

## Philadelphia-Camden-WilmingtonPA-NJ-DE-MDMSA-PATTERNS-2021_01-2021-12-17

```{r home_panel_summary, warning=FALSE}
home_panel_summary <- vroom("D:/OneDrive/WORK/Upenn/Spring_MUSA_801_Practicum/PPR - Safegraph/Data/SG_Data/SafeGraph Data Purchase Dec-16-2021/Philadelphia-Camden-WilmingtonPA-NJ-DE-MDMSA-PATTERNS-2021_01-2021-12-17/home_panel_summary.csv")
home_panel_summary
```

```{r normalization_stats, warning=FALSE}
normalization_stats <- vroom("D:/OneDrive/WORK/Upenn/Spring_MUSA_801_Practicum/PPR - Safegraph/Data/SG_Data/SafeGraph Data Purchase Dec-16-2021/Philadelphia-Camden-WilmingtonPA-NJ-DE-MDMSA-PATTERNS-2021_01-2021-12-17/normalization_stats.csv")
normalization_stats
```

```{r patterns, warning=FALSE}
patterns <- vroom("D:/OneDrive/WORK/Upenn/Spring_MUSA_801_Practicum/PPR - Safegraph/Data/SG_Data/SafeGraph Data Purchase Dec-16-2021/Philadelphia-Camden-WilmingtonPA-NJ-DE-MDMSA-PATTERNS-2021_01-2021-12-17/patterns.csv")
patterns
```

```{r visit_panel_summary, warning=FALSE}
visit_panel_summary <- vroom("D:/OneDrive/WORK/Upenn/Spring_MUSA_801_Practicum/PPR - Safegraph/Data/SG_Data/SafeGraph Data Purchase Dec-16-2021/Philadelphia-Camden-WilmingtonPA-NJ-DE-MDMSA-PATTERNS-2021_01-2021-12-17/visit_panel_summary.csv")
visit_panel_summary
```
